# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08101c16215803a35d47db8c61a0214ee7ef0c598757079ef937dda37274cd42e6890247678eef2068d3c5f1383e2cb0f80a546e6205a75d55a69a15fb4e16d9

test:
  secret_key_base: e0e8d84b1e47943b23e54072e4da4f8b96f00aa1e69f9c4e8d1d4a4c12693bef05f6994cce7234b87067c4c82eaa1c5f0e516aa607076f0b589ae4acf559a25b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
